source 'https://github.com/CocoaPods/Specs.git'

workspace 'MKApp.xcworkspace'
project 'MKApp.xcodeproj'

#target :MKCombineLoadingAnimation do
#  platform:ios,'9.0'
#  project 'devDemo/MKCombineLoadingAnimation/MKCombineLoadingAnimation.xcodeproj'
#  pod 'MKAppKit/MKCombineLoadingAnimation', :path => '../'
#end

target 'MKApp' do
  platform:ios,'9.0'
  pod 'MKAppKit/MKCombineLoadingAnimation', :path => '../'
  pod 'MKAppKit/MKDropdownMailTF', :path => '../'
  pod 'MKAppKit/MKDiffuseMenu', :path => '../'
#  pod 'MKAppKit/MKLaunchMonitor', :path => '../'
#  pod 'MKAppKit/MKLaunchMonitor'
#  pod 'MKAppKit/MKCombineLoadingAnimation'
#  pod 'MKAppKit/MKDropdownMailTF'
#  pod 'MKAppKit/MKDiffuseMenu'
end
